# Generated by Django 5.1.4 on 2025-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
